_wandb:
    value:
        cli_version: 0.25.0
        e:
            18ziqpnbt91oxcqqbqss1dnqjxxygr94:
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "1967317549056"
                        used: "411159621632"
                email: davidjayfsu@gmail.com
                executable: /home/orl1/Repos/2DWalt/env/bin/python
                git:
                    commit: 10355e5eac47f971bdf8b021e922d0a1592954fc
                    remote: git@github.com:dmj17b/2DWalt.git
                gpu: NVIDIA GeForce RTX 4070 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 7680
                      memoryTotal: "12878610432"
                      name: NVIDIA GeForce RTX 4070 Ti
                      uuid: GPU-ef4844e9-7230-8d5f-08c8-08cc6f9f9d42
                host: orl1-US-Desktop-Aegis-RS
                memory:
                    total: "33475276800"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /home/orl1/Repos/2DWalt/train.py
                python: CPython 3.12.3
                root: /home/orl1/Repos/2DWalt
                startedAt: "2026-03-27T14:27:19.910441Z"
                writerId: 18ziqpnbt91oxcqqbqss1dnqjxxygr94
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 16
            "4": 3.12.3
            "5": 0.25.0
            "12": 0.25.0
            "13": linux-x86_64
action_repeat:
    value: 5
batch_size:
    value: 1024
discounting:
    value: 0.995
entropy_cost:
    value: 0.01
episode_length:
    value: 1000
learning_rate:
    value: 0.0001
normalize_observations:
    value: true
num_envs:
    value: 4096
num_evals:
    value: 100
num_minibatches:
    value: 32
num_timesteps:
    value: 1000000
num_updates_per_batch:
    value: 16
reward_scaling:
    value: 1
unroll_length:
    value: 30
